/**
 * Terms of service.
 *
 * Also required by Google before an OAuth app can leave "Testing".
 */
export const metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16 text-neutral-800 dark:text-neutral-200">
      <h1 className="mb-2 text-3xl font-semibold">Terms of Service</h1>
      <p className="mb-10 text-sm text-neutral-500">Last updated: 31 August 2026</p>

      <section className="space-y-4 leading-relaxed">
        <h2 className="text-xl font-semibold">Scope</h2>
        <p>
          This application is a private personal assistant operated by one individual for their own
          use. It is not offered as a service to anyone else, and no other person is permitted to
          create an account or use it.
        </p>

        <h2 className="pt-6 text-xl font-semibold">No warranty</h2>
        <p>
          The application is provided as is, with no guarantee of availability, accuracy or fitness
          for any purpose. It relies on third-party services that may change or become unavailable.
        </p>

        <h2 className="pt-6 text-xl font-semibold">Automated output</h2>
        <p>
          Responses are generated by language models and may be inaccurate. Nothing produced here
          should be relied on as professional advice of any kind.
        </p>

        <h2 className="pt-6 text-xl font-semibold">Ending use</h2>
        <p>
          The operator may stop using or shut down the application at any time. Connected Google
          access can be revoked at any point from the Google Account permissions page.
        </p>

        <h2 className="pt-6 text-xl font-semibold">Contact</h2>
        <p>tayyabeh1807@gmail.com</p>
      </section>
    </main>
  );
}
