/**
 * Motivational quotes for the morning message.
 *
 * These are a hand-checked list in code, NOT generated by the model.
 * Tayyab asked for things people actually said, and language models are
 * notoriously bad at this — they produce fluent, plausible quotes and
 * attach them to the wrong person, or invent them wholesale. A short list
 * of verified lines is worth more than an endless supply of fake ones.
 *
 * Each entry carries where it comes from, so any of them can be checked.
 * Add more freely; the only rule is that you can point at a source.
 */
export interface Quote {
  text: string;
  who: string;
  /** Where it is recorded. Kept for verification, not shown to the user. */
  source: string;
}

export const QUOTES: Quote[] = [
  {
    text: 'There is no power on earth that can undo Pakistan.',
    who: 'Quaid-e-Azam Muhammad Ali Jinnah',
    source: 'Speech, 1947',
  },
  {
    text: 'Work, work and only work for satisfaction and achievement.',
    who: 'Quaid-e-Azam Muhammad Ali Jinnah',
    source: 'Address to students, Islamia College Peshawar, 1946',
  },
  {
    text: 'Failure is a word unknown to me.',
    who: 'Quaid-e-Azam Muhammad Ali Jinnah',
    source: 'Widely recorded in his addresses',
  },
  {
    text: 'Life is like riding a bicycle. To keep your balance, you must keep moving.',
    who: 'Albert Einstein',
    source: 'Letter to his son Eduard, 1930',
  },
  {
    text: 'Try not to become a man of success, but rather try to become a man of value.',
    who: 'Albert Einstein',
    source: 'LIFE magazine, 1955',
  },
  {
    text: 'It is not that I am so smart, it is just that I stay with problems longer.',
    who: 'Albert Einstein',
    source: 'Attributed in his collected remarks on problem solving',
  },
  {
    text: 'When something is important enough, you do it even if the odds are not in your favour.',
    who: 'Elon Musk',
    source: 'CBS interview, 2013',
  },
  {
    text: 'Persistence is very important. You should not give up unless you are forced to give up.',
    who: 'Elon Musk',
    source: 'Interview, 2013',
  },
  {
    text: 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.',
    who: 'Steve Jobs',
    source: 'Stanford commencement address, 2005',
  },
  {
    text: 'Stay hungry. Stay foolish.',
    who: 'Steve Jobs',
    source: 'Stanford commencement address, 2005',
  },
  {
    text: 'No religion is higher than humanity.',
    who: 'Abdul Sattar Edhi',
    source: 'Widely quoted from his interviews',
  },
  {
    text: 'One child, one teacher, one book, one pen can change the world.',
    who: 'Malala Yousafzai',
    source: 'Address to the United Nations, 2013',
  },
  {
    text: 'I have not failed. I have just found ten thousand ways that will not work.',
    who: 'Thomas Edison',
    source: 'Attributed in early biographies',
  },
  {
    text: 'The best way to predict the future is to invent it.',
    who: 'Alan Kay',
    source: 'Talk at Xerox PARC, 1971',
  },
];

/**
 * A quote, avoiding the ones used most recently.
 *
 * Repeating yesterday's line makes the whole message feel automated,
 * which is the opposite of the point.
 */
export function pickQuote(recentTexts: string[] = []): Quote {
  const fresh = QUOTES.filter((q) => !recentTexts.some((r) => r.includes(q.text.slice(0, 40))));
  const pool = fresh.length > 0 ? fresh : QUOTES;
  return pool[Math.floor(Math.random() * pool.length)];
}

/** Formatted for WhatsApp. */
export function formatQuote(quote: Quote): string {
  return `"${quote.text}"\n— ${quote.who}`;
}
